### ISSUE TITLE
 set of examples to cover

### ISSUE THREAD

**Issue by remiadon** [Inria-Visages/BIDS-prov#3]
Can we agree on a set of examples to cover

For now I have only considered the first few examples from the ["Dataset and examples" chapter from the SPM12 documentation](https://www.fil.ion.ucl.ac.uk/spm/doc/spm12_manual.pdf#part.7).

@cmaumet  it would probably be easier if we designate a set of examples in advance, along with a few mandatory fields in each example.

**Comment by cmaumet** [comment]
Yes!! We could start with the ones in: https://github.com/incf-nidash/nidmresults-examples

**Comment by remiadon** [comment]
@cmaumet  can you pick on specific example pointing to the SPM12 doc, or any kind of documentation ? I don't know where examples from nidm-results come from

**Comment by cmaumet** [comment]
@remiadon: those examples are nice because they cover a lot of different use cases in fMRI. I'm happy to help out recovering the corresponding pipelines. As a start, can you read the manuscript at: http://dx.doi.org/10.3389/fninf.2016.00024 if you have not done it already? For each example, the code used to run the analysis should be available in the same GitHub repo, (see "Data sources" in the paper).
